### ISSUE TITLE
SwiftyPing causes crash when resuming from suspended state

### ISSUE THREAD

**Issue by MQLiu** [samiyr/SwiftyPing#15]
Repetition steps：
1、open app and start ping
2、app enter to background
3、lock your iphone and wait more than 10s
4、unlock your iphone and reopen app
5、crash

**Comment by samiyr** [comment]
Thank you for bringing this issue to my attention. It turns out to be a very obscure bug, which DTS was fortunately able to identify. 

The underlying issue is that when the app begins the transition to the suspended state, the socket resources are reclaimed. However, once the app resumes foreground and tries to use the socket, the system triggers a SIGPIPE signal. For some reason, this type of crash doesn't generate a crash report, making this a wonderful bug to try to debug :)

This bug is now partially fixed by enabling the flag 'SO_NOSIGPIPE' on the socket. This flag ensures that instead of silently crashing, the socket simply returns an error, which can be handled gracefully. For SwiftyPing, this means throwing the error `PingError.requestError`.

However, to really fix this bug, pinging should be halted when entering the background. This is because of all the funky things that can happen when using the network stack in the background (see https://developer.apple.com/library/archive/technotes/tn2277/_index.html). To aid in this, I have added a new instance function called `haltPinging()`, which not only stops pinging but also destroys the socket. `startPinging()` has also been updated to handle the destroyed socket when resuming. Thus, every app is responsible for halting the pinger(s) when entering to the background. While the background to foreground transition should no longer cause a crash, it will cause some other side effects, such as high CPU usage and erratic pinging behavior. By default, the pinger instances will monitor for app stage changes on iOS and act accordingly. This behavior can be overridden by setting the new `PingConfiguration.handleBackgroundTransitions` to false.

So, all in all, the bug should be fixed now, the crash shouldn't occur under any circumstances and by default, app state changes are handled to halt and unhalt pinging when necessary, though this behavior can be overridden.

**Comment by MQLiu** [comment]
![1603434823926](https://user-images.githubusercontent.com/15275246/96964876-cfe4d180-153d-11eb-8f55-442e37913734.jpg)
Hi,I'm using the latest code, but I'm still getting crash reports

**Comment by samiyr** [comment]
I was able to reproduce a crash in the `CFRunLoopSourceInvalidate` call in the `didEnterBackground()` function and have fixed that in the latest release (v1.1.7). However, I'm not 100% sure that's the same as the one you've received. I'll close this for now, but let me know if you're still experiencing crashes and I'll look into it.
